.eslintrc, package.json, src/App.test.js, src/context/exchange.context.js, src/routes/Evodex/BackLayers/ExchangeBackLayer.js, src/routes/Evodex/SubmenuTopbar.js, src/utils/evolutiondex.js, yarn.lock
- Resolve #24
- yarn
- yarn start
- open http://localhost:3000
- navigate to http://localhost:3000/evodex/exchange
- click or tap a token pair from the list
=> chore: preserve input amount on switch token pair

src/components/InputTextAndSelect/InputTextAndSelect.js, src/routes/Evodex/BackLayers/ExchangeBackLayer.js, src/routes/Evodex/BackLayers/FeeBackLayer.js, src/routes/Evodex/BackLayers/LiquidityBackLayer.js
- Resolve #26
- yarn
- yarn start
- open http://localhost:3000
- navigate to http://localhost:3000/evodex/exchange
- pick a token to "Give" and a token to "Receive"
=> fix: same "Token" selected for exchange

src/components/InputTextAndSelect/InputTextAndSelect.js
- Use MUI component to refactor InputTextAndSelect component
- Change background Color and border Bottom color
- yarn start
- go to `http://localhost:3000`
=> Refactor inputAndSelect component

src/components/CollapseSection.js, src/components/InputTextAndSelect/InputTextAndSelect.js, src/routes/Evodex/BackLayers/ExchangeBackLayer.js, src/utils/evolutiondex.js, yarn.lock
- Resolve #32 
- yarn
- yarn start
- go to `http://localhost:3000`
=> chore: add advance info section for exchange view

src/components/InputTextAndSelect/InputTextAndSelect.js, src/routes/Evodex/BackLayers/ExchangeBackLayer.js, src/routes/Evodex/BackLayers/FeeBackLayer.js, src/routes/Evodex/BackLayers/LiquidityBackLayer.js, src/routes/Evodex/BackLayers/index.js, src/routes/Evodex/Evodex.js, src/theme/palette.js, src/utils/getScatterError.js
- Resolve #38  
- yarn
- yarn start
- go to https://deploy-preview-54--evodex.netlify.app/evodex/exchange
- exchange a token
- check the snackbar message
=> fix: update snackbar position to center bottom

package.json, src/routes/Evodex/Evodex.js, yarn.lock
Update eoscr-component latest version 
- yarn
- yarn start
- go to `http://localhost:3000`
=> Update eoscr-component library

src/language/en/faq.md, src/language/es/about.md, src/language/es/faq.md, src/routes/Evodex/BackLayer/Faq/FaqBackLayer.js
- Updated Page headers
- Initial content translation from english to git push, this still needs to be revised.
=> Update texts and Headers

.github/pull_request_template.md, src/language/en/en.json, src/language/es/es.json, src/routes/Evodex/BackLayer/About/AboutBackLayer.js, src/routes/Evodex/BackLayer/Exchange/ExchangeBackLayer.js, src/routes/Evodex/BackLayer/Faq/FaqBackLayer.js, src/routes/Evodex/BackLayer/Fee/FeeBackLayer.js, src/routes/Evodex/BackLayer/Liquidity/LiquidityBackLayer.js, src/routes/Evodex/BackLayer/RicardianContract/RicardianContractBackLayer.js, src/routes/Evodex/Evodex.js, src/routes/Evodex/FrontLayer/About/About.js, src/routes/Evodex/FrontLayer/Exchange/Exchange.js, src/routes/Evodex/FrontLayer/Faq/Faq.js, src/routes/Evodex/FrontLayer/Fee/Fee.js, src/routes/Evodex/FrontLayer/Liquidity/Liquidity.js, src/routes/Evodex/Sidebar.js, src/routes/Evodex/SubmenuTopbar.js, src/routes/NotFound/NotFound.js
- Set Internationalization json files
- Include logic to switch languages on evodex pages (#8)
- Add padding botton on FAQ's frontLayer (#73)
- Rename Ricardian Contract label (#75)
- Add Style to markdown pages (#76)
1. `yarn`
2. `yarn start`
3. go to `localhost:3000`
=> Add Internationalization (i18n)

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, .github/workflows/deploy.yml, package.json, src/language/en/about.md, src/language/en/en.json, src/language/es/about.md, src/language/es/es.json, src/language/es/faq.md, src/routes/Evodex/BackLayer/About/AboutBackLayer.js, yarn.lock
- Create Development Branch #82
- Production Web Hosting #70
- Evodex vs EvoDex #71
- Added GitHub Workflow for master branch deployment to GitHub Pages and EOS Mainnet
- Updated Package JSON fields
- Update UAL Anchor
- Update dev dependencies
- Fix Bug in About Page title
- Added Issue templates for Bugs and Features
- Made use of `EvoDex` consistent in all texts
1. Download Repo 
2. Run `yarn`
3. Run `yarn run`
=> Add GitHub Pages Deployment 

package.json, src/App.js, src/components/PageTitle/TitlePage.js, src/components/PageTitle/index.js, src/config/google-analitycs-module.js, src/containers/Main/Main.js, src/language/en/en.json, src/language/en/faq.md, src/language/es/about.md, src/language/es/es.json, src/language/es/faq.md, src/routes/Evodex/BackLayer/About/AboutBackLayer.js, src/routes/Evodex/BackLayer/Exchange/ExchangeBackLayer.js, src/routes/Evodex/BackLayer/Faq/FaqBackLayer.js, src/routes/Evodex/BackLayer/Fee/FeeBackLayer.js, src/routes/Evodex/BackLayer/Liquidity/LiquidityBackLayer.js, src/routes/Evodex/BackLayer/RicardianContract/RicardianContractBackLayer.js, src/routes/Evodex/BackLayer/index.js, src/routes/Evodex/Evodex.js, src/routes/Evodex/FrontLayer/index.js, src/routes/Evodex/Sidebar.js, src/routes/Evodex/SubmenuTopbar.js, src/routes/index.js, yarn.lock
- Add google analytics (#89)
- Add HTML page titles (#85)
- Fix margin left in backdrop titles (#83)
- Remove `evodex` from routes (#84)
1. yarn
1. yarn start
1. go to `localhost:3000`
=> Fix issues

src/config/google-analitycs-module.js
#29 # What does this PR do?
Updates to new GA property ID
=> update  google analytics config

package.json, public/CNAME
- add CNAME config file
- add site homepage
=> add domain config

package.json, public/CNAME, src/config/google-analitycs-module.js
- set CNAME value for GitHub Pages
- set site homepage for react web app build
=> set site homepage for react web app build

.github/workflows/deploy.yml
redirect default 404 page (`404.html`)  to `index,html`
=> update deploy script

.github/workflows/deploy.yml, package.json, yarn.lock
Versioning strategy #128 
- Triggers project build after new tag is created
- Adds version string as environmental variable for display in UI
- Creates release notes 
- Also updated some packages
1. Create a new version tag
1. Check release notes
=> ci(version): add gh actions version steps

README.md, package.json, src/components/Footer/TalkUsModal.js, src/routes/Evodex/Sidebar.js, src/routes/Evodex/SubmenuTopbar.js
Updates telegram channel path
1. check telegram link in sidebar
1. check telegram link in footer
1. check telegram link in readme
=> fix(links): update telegram channels links

.github/workflows/deploy.yml
Updates GH Workflow to include versioning strategy
=> ci(): update workflow to use GITHUB_TOKEN

public/index.html, src/containers/Main/Main.js, src/routes/Evodex/Evodex.js, src/routes/Evodex/FrontLayer/About/About.js, src/routes/Evodex/FrontLayer/Faq/Faq.js
- fix footer overlapping
- get view height on mobile browser
1. yarn
2. yarn start
3. go to localhost:3000
4. navigate to different pages and see the footer
=> View height on mobile browser

src/components/Button/Button.js, src/components/InputTextAndSelect/InputTextAndSelect.js
Update Styles #155 
- Button should switch to a lighter color on hover (not darker)
- Update font-weight for button
=> fix(styles): Adjusted button hover color

src/components/Footer/Footer.js, src/routes/Evodex/Evodex.js, src/routes/Evodex/FrontLayer/About/About.js, src/routes/Evodex/FrontLayer/Exchange/Exchange.js, src/routes/Evodex/FrontLayer/Faq/Faq.js, src/routes/Evodex/FrontLayer/Fee/Fee.js, src/routes/Evodex/FrontLayer/Liquidity/Liquidity.js, src/routes/Evodex/FrontLayer/RicardianContract/RicardianContract.js, src/routes/Evodex/FrontLayer/index.js
Add new footer style
1. yarn start
1. see footer
=> Add new footer style

README.md, src/language/es/es.json
Add versioning to readme #160
Spanish Translation Text Styles #159
- adjusts text styles in spanish to Title Case same as in english texts
- add versioning strategy to readme file
1. Read `readme.md`
1. Read spanish site
=> docs(readme): Added versioning information

README.md
No GH issue
Updates telegram channel link
1. click on telegram link on readme file
=> docs(readme): Updated telegram channel

.github/workflows/deploy.yml
No GH issue
Environmental variable with app name used for wallet integration was updated to match values registered with wallets.
1. Use scatter to log into the application
1. Evodex logo should appear in scatter
=> fix(UAL):Update app name to evodex.io

src/routes/Evodex/BackLayer/Exchange/ExchangeBackLayer.js
Resolve #156 
Fix an error when the user try to use the switch button and the tokens are empty
1. yarn start
2. navigate to http://localhost:3000/exchange
3. try to use the switch button without select a token
=> fix: error when no pools are present, resolve #156

.env.example, .github/workflows/deploy.yml, src/config/evodex.config.js, src/language/en/en.json, src/language/es/es.json, src/utils/axios.util.js, src/utils/evolutiondex.js
Resolve #124 
Add an axios interceptor to retry any request using the failover endpoint
1. set an invalid value for `REACT_APP_EVODEX_API_URL`
2. set a valid value for `REACT_APP_EVODEX_API_URL_FAILOVER`
3. yarn start
4. navigate to http://localhost:3000/exchange and check the network
=> feat: implement api failover endpoint, resolve #124

.env.example, .github/workflows/deploy.yml, src/config/ual.config.js
Sets failover endpoint env var
1. Disable main endpoint in backend service
1. Check https://jungle.evodex.io to see if token listings are sourced from failover endpoint
=> feat(API):Update api endpoints

src/routes/Evodex/BackLayer/Exchange/ExchangeBackLayer.js, src/utils/evolutiondex.js
Resolve #173
Allow type the desired amount ti receive  
1. yarn start
2. navigate to http://localhost:3000/exchange
3. type an amount for "You Receive" input
=> feat: allow type the amount to receive

src/components/InputTextAndSelect/InputTextAndSelect.js, src/language/en/en.json, src/language/es/es.json, src/routes/Evodex/BackLayer/Fee/FeeBackLayer.js
no GH issue
Sets a property for the placeholder text displayed in input fields.
1. Navigate to exchange  , placeholder should read "this amount"
1. Navigate to fee  , placeholder should read "this percentage"
=> fix(fees):Add placeholder property into text and select field

.github/ISSUE_TEMPLATE/bug_report.md, src/config/ual.config.js
- Added wallet to issue template
- replaced default values in UAL config
=> docs(bug reports): Added wallet to issue template

src/components/InputTextAndSelect/InputTextAndSelect.js, src/language/en/en.json, src/language/es/es.json, src/routes/Evodex/BackLayer/Exchange/ExchangeBackLayer.js, src/utils/evolutiondex.js
Resolve #80 
optimize ram using open action of token 2 so that the user pays for the RAM
1. yarn start
2. navigate to http://localhost:3000/exchange
3. exchange using a token that you do not have in your account
4. confirm that there is a action open in the details of the transaction
=> feat: optimize ram

src/language/en/en.json, src/language/es/es.json, src/routes/Evodex/BackLayer/Exchange/ExchangeBackLayer.js
Resolve #186 
Display the contract name for exchange view for each token
1. yarn
2. yarn start
3. go to http://localhost:3000/exchange
4. pick both tokens
=> feat: display contract name in exchange view

src/components/Footer/Footer.js, src/utils/evolutiondex.js
- Fix app version label broken
1. yarn start
=> Increase width version label

src/components/LanguageSelector/LanguageSelector.js, src/language/index.js, src/language/zh/about.md, src/language/zh/faq.md, src/language/zh/zh.json, src/ual.js, src/utils/getMarkdownByLanguage.js
Chinese Translation #90 
Wallet Testing #193
1. update ual-token-pocket config
2. add Chinese language
1. ual-token-pocket only support mainnet
=> update ual-token-pocket config & add Chinese language

src/routes/Evodex/Sidebar.js, src/routes/Evodex/SubmenuTopbar.js
Update Medium link
1. click on medium links
1. should tae you to https://medium.com/evodex-io
=> fix(medium): update links to oficial medium page

src/routes/Evodex/BackLayer/Exchange/ExchangeBackLayer.js, src/utils/commonStyles.js
- Fix UI issues
- Populate inputs select after table row click
1. yarn start
2. go to localhost:3000
3. click on any tokens pair table row
=> Click table row

public/index.html, src/containers/Main/Main.js
- Fix Responsive Evodex page
1. yarn
2. go to localhost:3000
3. test all breakpoints view
=> fix(): fix windows resize

package.json, src/components/InputTextAndSelect/InputTextAndSelect.js, src/language/en/en.json, src/language/es/es.json, src/language/zh/zh.json, src/routes/Evodex/BackLayer/Exchange/ExchangeBackLayer.js, src/routes/Evodex/BackLayer/Fee/FeeBackLayer.js, src/routes/Evodex/BackLayer/Liquidity/LiquidityBackLayer.js, yarn.lock
- Add input mask to Fee page (mask example 99.99% max value 100%)
- Add input mask to Exchange/Liquidity page (mask example 9999.2222 max value (2^62).4444)
- Refactor InputSelect component in order to add new properties such as suffix
- Add react-number-format
1. yarn
2. yarn start
3. go to localhost:3000
4. test input masks
=> Add input mask

src/routes/Evodex/Evodex.js, src/routes/Evodex/FrontLayer/index.js, src/routes/Evodex/Sidebar.js, src/routes/Evodex/Topbar.js
=> Fix eslint errors

src/components/InputTextAndSelect/InputTextAndSelect.js, src/routes/Evodex/BackLayer/Exchange/ExchangeBackLayer.js
- Reset values when pair change
1. yarn start
1. test backlayer pages
=> Reset values when pair change

src/utils/evolutiondex.js
Changing some function to the UAL standard API:
https://github.com/EOSIO/universal-authenticator-library/blob/master/src/User.ts#L68
https://github.com/EOSIO/universal-authenticator-library/blob/master/src/User.ts#L29
1.
1.
1.
=> Fix using standard API of UAL

src/components/InputTextAndSelect/InputTextAndSelect.js, src/language/en/en.json, src/language/es/es.json, src/language/ru/ru.json, src/language/zh/zh.json, src/routes/Evodex/BackLayer/Exchange/ExchangeBackLayer.js, src/routes/Evodex/BackLayer/Exchange/HelpeText.js, src/routes/Evodex/BackLayer/Fee/FeeBackLayer.js, src/routes/Evodex/BackLayer/Liquidity/LiquidityBackLayer.js, src/utils/evolutiondex.js
N/A
- fix calculation for you give input from you receive
- clear the second input when the first one its empty 
- Show wallet for second token
- Show error message for exchange form
- limit decimal input according to the token precision 
- Filter pairs from "my pools" list when the user no longer have participation on it
1. yarn
2. yarn start
3. type a value in "You Receive" field 
4. execute the token exchange 
5. check your account, you should get the same amount that you typed for "You Receive" field
=> fix: calculation for you give input from you receive

src/components/InputTextAndSelect/InputTextAndSelect.js, src/language/en/en.json, src/language/es/es.json, src/language/ru/ru.json, src/language/zh/zh.json, src/routes/Evodex/BackLayer/Exchange/ExchangeBackLayer.js, src/routes/Evodex/BackLayer/Fee/FeeBackLayer.js, src/routes/Evodex/BackLayer/Liquidity/LiquidityBackLayer.js, src/utils/evolutiondex.js
N/A
Fix wrong value change for asset 
1. yarn start
2. navigate to http://localhost:3000/exchange
3. enter a value with more than 10 characters
=> fix: wrong value for asset input

src/config/ual.config.js, src/routes/Evodex/FrontLayer/RicardianContract/RicardianContract.js
Fix hardcode url for ricardian contracts
1. yarn
2. yarn start
3. navigate to http://localhost:3000/ricardian-contract
4. check the info for each contract
=> fix: hardcoded url

src/language/en/en.json, src/language/es/es.json, src/language/ru/ru.json, src/language/zh/zh.json, src/routes/Evodex/BackLayer/Exchange/ExchangeBackLayer.js, src/utils/evolutiondex.js
Add the price impact for exchange 
1. yarn
2. yarn start
3. navigate to http://localhost:3000/exchange
4. pick a pair and enter a valid amount
=> feat: add price impact

src/language/en/en.json, src/language/es/es.json, src/language/ru/ru.json, src/language/zh/zh.json, src/routes/Evodex/BackLayer/Liquidity/LiquidityBackLayer.js, src/utils/evolutiondex.js
- show current supply value
- show user balance
1. yarn start
1. navigate to liquidity page and select a token pair
=> Show correct current supply value

src/routes/Evodex/BackLayer/Liquidity/LiquidityBackLayer.js, src/utils/eosapi.js, src/utils/evolutiondex.js
- Use `eosjs-api`  to get current supply
1. run yarn start
1. navigate to liquidity page and select a token pair
=> Current supply

package.json, src/config/ual.config.js, src/ual.js, yarn.lock
=> Add metamask UAL

.github/workflows/deploy.yml
=> fix(webapp): set correct env var value for version tag

package.json, yarn.lock
=> Update ual-metamask version

package.json, src/components/Footer/Footer.js, yarn.lock
=> Update anchor UAL library
